= 설정 파일

Lucy-XSS Filter의 필터링 규칙은 화이트리스트 방식으로 설정된다.
화이트리스트 방식은 허용되는 내용을 제외한 모든 부분을 필터링하여 새로운 공격 유형에 대해서도 대처 가능하다.
화이트리스트 설정 파일은 XML 형식으로 작성하며 상위 설정 파일을 상속하거나 오버라이딩 할 수 있다.

화이트리스트 설정 파일의 구조는 다음과 같다.

[source,xml]
----
<config xmlns="http://www.nhncorp.com/lucy-xss" extends="...">
    <elementRule>
    </elementRule>
    <attributeRule>
    </attributeRule>
    <elementGroup name="...">
    </elementGroup>
    <attributeGroup name="...">
    </attributeGroup>
</config>
----

'config'는 최상위 요소(root element)로서 다음과 같은 속성과 내용을 포함한다.

* `xmlns` : 디폴트 네임스페이스
* `extends` : 상속 받을 설정 파일 이름(해당 파일 내에 정의된 “config”를 모두 상속받는다.)
* `elementRule` : 적용 가능한 모든 요소에 대한 필터링 규칙을 설정한다.
* `attributeRule` : 적용 가능한 모든 속성에 대한 필터링 규칙을 설정한다.
* `elementGroup` : 요소의 집합을 정의한다. (DOM 방식에서만 사용)
* `attributeGroup` : 속성의 집합을 정의한다. (DOM 방식에서만 사용)
* `filteringTagInComment` : HTML 주석(<!-- 주석 -->) 내에 존재하는 요소(HTML 태그)에 대한 필터링 여부와 타입을 설정한다.

== elementRule
적용 가능한 모든 요소에 대한 필터링 규칙을 정의하며 다음과 같이 작성한다.

[source,xml]
----
<elementRule>
    …
    <element name="a" endTag="true" override="true" disable="false">
        <attributes>
            …
            <ref name="Common" />
            …
        </attributes>
        <elements>
            …
            <ref name="Inline">
                <excludes>
                    <ref name="a" />
                </excludes>
            </ref>
            …
        </elements>
        <listener>com.nhncorp.security.xss.XXXListener</listener>
        …
    </element>
    …
</elementRule>
----


* `elementRule` : 하나 이상의 element 요소로 정의되며, element 필터링 규칙에 없는 요소는 필터링 대상이 된다.
* `element` : 하나의 요소에 대한 필터링 규칙을 설정한다.
** `name` : 요소 이름
** `endTag` : End Tag의 존재 유무를 `true/false` 로 설정한다. 디폴트는 `false` 이다. (DOM 방식에서만 사용)
** `override` : 'extends' 속성에 기술한 상위 설정 파일에 동일한 설정이 있으면 그 설정을 상속받을지를 설정한다. 디폴트는 `true`이다.
** `disable` : `name` 에 설정된 요소를 `elementRule` 에서 제거할지 설정한다. 디폴트는 `false` 이다.
** `removeTag` : 필터링 결과물에서 element의 삭제 유무를 `true/false` 로 설정한다. 디폴트는 `false` 이다. 가령 <body>의 내용만 사용되는 경우, <html>, <head>, <body> 등을 삭제하는데 사용될 수 있다.
* `attributes` : element의 속성을 입력한다. (DOM 방식에서만 사용)
* `elements` : element의 하위 요소를 입력한다. (DOM 방식에서만 사용)
* `listener` : 이 화이트리스트 설정 파일의 설정만으로 해당 요소를 필터링할 수 없는 경우, `com.nhncorp.lucy.security.xss.event.ElementListener` 인터페이스를 상속하여 구현한 클래스 이름을 입력한다.
* `ref` : elementRule 또는 attributeRule에 설정된 element/attribute에 대한 레퍼런스이다. elementGroup 또는 attributeGroup을 레퍼런스할 수도 있다.
* `name` : 레퍼런스 이름.
* `excludes` : ref가 elementGroup 또는 attributeGroup의 레퍼런스인 경우 지정한 ref를 제외시킨다. (DOM 방식에서만 사용)

== attributeRule
적용 가능한 모든 속성에 대한 필터링 규칙을 정의하며, 다음과 같이 작성한다.

[source,xml]
----
<attributeRule>
    …
    <attribute name="class" override="true" disable="false">
        <allowedPattern><![CDATA[…..]]></allowedPattern>
    </attribute>
    <attribute name="class" override="true" disable="false" base64Decoding="true">
        <notAllowedPattern><![CDATA[…..]]></allowedPattern>
    </attribute>
    …
</attributeRule>
----

* `attributeRule` : 하나 이상의 하위 attribute 태그를 가지는 부모 태그이다.
* `attribute` : 하나의 속성에 대한 필터링 규칙을 설정한다.
** `name` : 속성 이름
** `override` : config의 'extends' 속성에 설정한 상위 설정 파일에 동일한 설정이 있으면 그 설정을 상속받을지를 결정한다. 디폴트는 `true` 이다.
** `disable` : name에 설정된 속성을 attributeRule에서 제거할지 설정한다. 디폴트는 `false` 이다.
** `Base64Decoding` : 속성 값에 필터링 규칙을 적용하기 전에 base64 디코딩 수행 여부를 설정한다. 디폴트는 `false` 이다.
** `exceptionTagList` : attribute가 disable 설정이지만, 특정 태그에서는 해당 attribute 사용을 허용 하고 싶을 경우 사용한다. 가령, `<attribute name="class" disable="true" />` 설정이 되어 있을 경우, 모든 태그에서 class 속성이 허용되지 않는다. 즉 기존에는 table 태그에서만 class 속성을 허용하고 싶을 경우 방법이 없었다. 하지만 이제는 아래와 같이 exceptionTagList 속성을 사용하면 table에서 class 속성을 사용할 수 있도록 예외처리가 가능하다.
* `allowedPattern` : 속성 값으로 허용되는 정규 표현식(regular expression)을 입력한다. 패턴에 해당되지 않는 모든 속성 값은 필터링 된다.
* `notAllowedPattern` : 속성 값으로 허용되지 않는 정규 표현식을 입력한다. 패턴에 해당되는 모든 속성 값은 필터링 된다.
attributeRule에 notAllowedPattern과 allowedPattern이 동시에 정의되어있을 경우 notAllowedPattern을 기본 적용 후 allowedPattern으로 예외처리를 할 수 있다. <br> 예를 들어 현재 href 속성 값에는 디폴트 보안설정(lucy-xss-superset.xml 또는 lucy-xss-superset-sax.xml)에 따라 javascript: 패턴이 올 수 없다. <br> 하지만 서비스 응용에 따라 특정 javascript 메소드를 허용하고자 할 때, 해당 메소드를 allowedPattern으로 추가하면 된다.

== elementGroup/attributeGroup(DOM 방식에서만 사용)
elementGroup과 attributeGroup은 각각 elementRule과 attributeRule에 설정된 element/attribute에 대한 레퍼런스의 집합을 그루핑하는 역할을 담당한다.
다음과 같이 작성한다.

[source,xml]
----
<elementGroup name="Inline">
    …
    <ref name="a" />
    …
</elementGroup>

<attributeGroup name="Core">
    …
    <ref name="class" />
    …
</attributeGroup>
----

* `elementGroup/attributeGroup` : elementRule과 attributeRule에 설정된 element/attribute들에 대한 레퍼런스의 집합을 그루핑한다.
** `name` : 그룹 이름
** `override` : config의 'extends' 속성에 기술한 상위 설정 파일에 동일한 설정이 있으면 그 설정을 상속받을지 설정한다. 디폴트는 `true` 이다.
* `ref` : elementRule 또는 attributeRule에 기술된 element/attribute에 대한 레퍼런스이다. 다른 elementGroup/attributeGroup을 참조할 수도 있다.

== IEHackExtension(IE핵 태그)
Lucy-XSS Filter 에서는 IE핵을 주석이 아닌 별도의 태그로 인식하며, 어떤 태그에도 올 수 있도록 허용 하고 있다.
혹 IE 핵 태그를 삭제(비 허용)할 필요가 있다면, IE 핵 태그를 disable 시키도록 설정하면 된다.
기본적으로 IE핵 태그의 자식 컨텐츠는 삭제되지 않는다.
자식 컨텐츠를 삭제하고 싶다면 별도의 ElementListener를 구현하거나 Xss Filter에서 기본적으로 제공하는 ContentsRemoveListener를 IE 핵 태그에 리스너를 아래와 같이 설정하면 된다.
ContentsRemoveListener는 XssFilter 객체일 경우에만 사용 가능하다. XssSaxFilter에서는 제대로 동작하지 않는다.

[source,xml]
----
…
<element name="IEHackExtension" disable=”true”>
	   <listener>com.nhncorp.lucy.security.xss.listener.ContentsRemoveListener</listener>
</element>
…
----

IEHackExtension은 Element를 상속 받은 클래스로서 Element에서 사용하는 속성 및 메소드 모두 사용 가능하다.

== blockingPrefix

Lucy-XSS Filter에서는 화이트리스트에 포함되지 않은 부분에 대해 `<`, `>` 를 `&#38;&#108;&#116;&#59;`, `&#38;&#103;&#116;&#59;` 로 치환하지 않고 태그에 prefix를 적용할 수 있다. 아래 설정을 적용하면 허용되지 않은 `<notAllowed>` 태그를 `<xnotAllowed>` 로 치환한다.

[source,xml]
----
<blockingPrefix enable="true" prefix="x"/>
----

== filteringTagInComment
Lucy-XSS Filter에서는 HTML 주석(<!-- 주석문 -->)내에 존재하는 HTML 태그에 대해서 XSS 필터링 여부를 설정하고 타입을 지정할 수 있다.
설정을 명시하지 않은 경우, 주석 내에 존재하는 괄호 `<` , `>` 은 `&#38;&#108;&#116;&#59;` , `&#38;&#103;&#116;&#59;` 으로 변환하는 것을 디폴트로 한다.
주석 내 필터링을 통해 검출된 공격 패턴에 대해서는 동작하지 않도록 필터링할 뿐, 주석 설명은 제공하지 않는다.

[source,xml]
----
…
<!-- // type1 : 가장 보안 수준이 높은 타입, 모든 태그를 필터링한다. (디폴트 타입, 권장) // -->
<filteringTagInComment enable="true" type="strict"/>

<!-- // type2 : 주석 밖의 태그에 적용되는 필터링 규칙과 동일한 규칙을 사용해 태그를 필터링 한다.// -->
<filteringTagInComment enable="true" type="config"/>

<!-- // type3 : 주석 내에 존재하는 태그를 그대로 보존한다. (비권장)// -->
<filteringTagInComment enable="false"/>
…
----

== 테스트
규칙이 의도대로 설정되었는지는 테스트 코드로 반드시 검증해 본다.
[source,java]
----
XssFilter filter = XssFilter.getInstance("lucy-xss-superset.xml");

@Test
public void testDirtyCodeFiltering() throws Exception {
    String dirty = "<script></script>";
    String clean = filter.doFilter(dirty);
    String expected = "&lt;script&gt;&lt;/script&gt;"; // 예상 문자열
    assertEquals(expecte, clean);
}
----


