= XssFilter (DOM 방식)
DOM 방식의  XssFilter를 위해 기본 제공되는 화이트리스트 설정 파일은 아래와 같다.

* lucy-xss-default.xml
** HTML 4.0을 기본으로 하며, HTML 5.0과 Internet Explorer에 특화된 몇 가지 명세를 추가한 기본 설정 파일이다.
** lucy-xss-x.x.x.jar 파일 내부에 포함되어 배포된다.
* lucy-xss-superset.xml :
** lucy-xss-default.xml을 상속받아 작성된 파일이다. 회사의 보안부서에서 기초 정책을 저으이하고 있다.
** 이 저장소의 conf 디렉토리 아래에서 배포된다.

`XssFilter.getInstance()` 메서드로 설정 파일을 지정하지 않은 경우에는 `lucy-xss-superset.xml` 파일을 클래스패스에서 찾아 읽는다.
`lucy-xss-superset.xml` 파일이 존재하지 않으면, jar 파일에 내장된 `lucy-xss-default.xml` 을 읽어 들인다.

[source,java]
----
XssFilter filter = XssFilter.getInstance();
----

서비스별로 특수한 정책을 설정해야한다면 다음과 같이 설정파일을 작성한다.

`lucy-xss-superset.xml` 을 상속받도록 extends 속성을 추가한다.

[source,xml]
----
<config xmlns="http://www.nhncorp.com/lucy-xss" extends="lucy-xss-superset.xml">

</config>
----

애플리케이션의 성격에 따라서 상위 설정 파일에서 정의한 규칙을 재정의하거나 새로운 규칙을 추가한다.

[source,xml]
----
<config xmlns="http://www.nhncorp.com/lucy-xss" extends="lucy-xss-superset.xml">
    <elementRule>
    </elementRule>
    <attributeRule>
    </attributeRule>

    <elementGroup name="…">
    </elementGroup>
    <attributeGroup name="…">
    </attributeGroup>
</config>
----

입력 파라미터로 지정한 XSS 설정파일("lucy-xss.xml")을 읽어 들여 인스턴스를 생성한다.

[source,java]
----
XssFilter otherFilter = XssFilter.getInstance("lucy-xss.xml");
----

공격 패턴 검출 시 디버그를 위해 추가되는 주석문을 표시하지 않기 위해서는 다음과 같이 인스턴스를 생성한다.

[source,java]
----
XssFilter filterNoComment = XssFilter.getInstance(true);
----

또는

[source,java]
----

XssFilter otherFilterNoComment = XssFilter.getInstance("lucy-xss.xml", true);
----

`doFilter()` 메서드로 필터링을 수행한다.

[source,java]
----
String clean = filter.doFilter(String dirty);
----


주요 메서드들은 다음과 같다.

* `static XssFilter getInstance()` : “lucy-xss-superset.xml”을 기본 설정 파일로 사용하며, “lucy-xss-superset.xml”이 루트 클래스패스에 없으면 XSS Filter 라이브러리(lucy-xss-1.x.x.jar) 내에 있는 “lucy-xss-default.xml”의 설정 내용을 사용한다. 공격 패턴 검출 시 추가되는 주석문을 제거하는 인스턴스 변수(withoutComment)는 디폴트로 false 값이 지정되고 공격 패턴 검출 시 주석문이 표시된다.
* `static XssFilter getInstance(boolean withoutComment)` : getInstance() 메소드와 동일하게 동작한다. 단, 공격 패턴 검출 시 추가되는 주석문 삭제를 나타내는 인스턴스 변수값이 withoutComment 파라미터 값에 의해 결정된다. true 이면 주석문을 표시하지 않는다. 공격 패턴 검출 시 추가되는 주석문  <br> 1. 허용되지 않은 태그 사용 시 <!-- Not Allowed Tag Filtered --> <br> 2. 허용되지 않은 속성 사용 시 <!-- Not Allowed Attribute Filtered --> <br> 3. 삭제 설정 된 태그 사용 시  <!-- Removed Tag Filtered ( 삭제 된 태그 ) -->|
* `static XssFilter getInstance(String fileName)` : 이 메소드는 입력한 파일 이름에 해당하는 설정 파일을 사용하여 생성한 Lucy-XSS Filter 객체를 반환한다. 해당 파일을 찾을 수 없는 경우, 예외(exception)를 발생시킨다. 공격 패턴 검출 시 추가되는 주석문을 제거하는 인스턴스 변수는 디폴트로 false 값이 지정되어 주석문이 표시된다.|
* `static XssFilter getInstance(String filename, boolean withoutComment)` : getInstance(java.lang.String fileName) 메소드와 동일하게 동작한다. 단, 공격 패턴 검출 시 추가되는 주석문 삭제를 나타내는 인스턴스 변수값이 withoutComment 파라미터 값에 의해 결정된다. true 이면 주석문을 표시하지 않는다.|
* `String doFilter(String dirty)` : 이 메소드는 XSS 코드가 포함된 HTML 문자열을 신뢰할 수 있는 코드로 변환하거나 삭제한 후 결과물을 String으로 리턴한다.
* `String doFilter(String dirty, Writer writer)` : 이 메소드는 XSS 코드가 포함된 HTML 문자열을 신뢰할 수 있는 코드로 변환하거나 삭제한 후 결과물을 인자로 받은 writer객체에 write한다. 즉 외부에서 writer를 제어할 수 있는 인터페이스를 제공한다.
* `String doFilter(String tagName, String attName, String dirtyAttValue)` : 이 메소드는 특정 HTML 요소 내의 속성 값으로 삽입되는 XSS 코드를 신뢰할 수 있는 코드로 변환하거나 삭제한다.|

메모리에 민감한 서비스에서는 XssFilter 객체 생성시 getInstance(String filename, boolean withoutComment)메소드의 withoutComment 인자로 true 를 넘기길 권장한다.
공격 패턴 검출 시 추가되는 주석문 생성 옵션을 끌 경우 메모리 사용량을 약 5% 줄일 수 있다.
사용

[source,java]
----
XssFilter filter = XssFilter.getInstance(“lucy-xss-superset.xml”, true);
----